### ISSUE TITLE
Can not unset or set empty environment variables.

### ISSUE THREAD

**Issue by parched** [cmake-maven-project/cmake-maven-project#11]
If you try to set an environment variable to empty it throws a null pointer exception.

I think this is because maven treats empty as `null` and `ProcessBuilder.environment()` doesn't handle `null` values.

A solution would be to check for any keys with `null` values in `environmentVariables` and then remove them from `ProcessBuilder.environment()`

**Comment by cowwoc** [comment]
@parched I should be able to fix this quickly if you provide a stack-trace.

**Comment by parched** [comment]
@cowwoc Like this?
```
$ mvn -e package
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building XXXX 0.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- cmake-maven-plugin:2.8.11-b4:generate (generate) @ XXX ---
[INFO] Configured Artifact: com.googlecode.cmake-maven-project:cmake-binaries:linux:2.8.11-b4:jar
[INFO] cmake-binaries-2.8.11-b4-linux.jar already unpacked.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.702s
[INFO] Finished at: Fri Dec 02 16:56:16 GMT 2016
[INFO] Final Memory: 12M/303M
[INFO] ------------------------------------------------------------------------
 [ERROR] Failed to execute goal com.googlecode.cmake-maven-project:cmake-maven-plugin:2.8.11-b4:generate (generate) on project XXXX: Execution generate of goal com.googlecode.cmake-maven-project:cmake-maven-plugin:2.8.11-b4:generate failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.googlecode.cmake-maven-project:cmake-maven-plugin:2.8.11-b4:generate (generate) on project XXXX: Execution generate of goal com.googlecode.cmake-maven-project:cmake-maven-plugin:2.8.11-b4:generate failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution generate of goal com.googlecode.cmake-maven-project:cmake-maven-plugin:2.8.11-b4:generate failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:115)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.NullPointerException
	at java.lang.ProcessEnvironment.validateValue(ProcessEnvironment.java:120)
	at java.lang.ProcessEnvironment.access$400(ProcessEnvironment.java:61)
	at java.lang.ProcessEnvironment$Value.valueOf(ProcessEnvironment.java:203)
	at java.lang.ProcessEnvironment$StringEnvironment.put(ProcessEnvironment.java:243)
	at java.lang.ProcessEnvironment$StringEnvironment.put(ProcessEnvironment.java:221)
	at java.util.AbstractMap.putAll(AbstractMap.java:281)
	at com.googlecode.cmakemavenproject.GenerateMojo.execute(GenerateMojo.java:156)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
	... 20 more
[ERROR] 
[ERROR] 
```

**Comment by cowwoc** [comment]
I am having a hard time reproducing this problem. I tried this configuration:
```
<environmentVariables>
	<key></key>
	<key2>null</key2>
</environmentVariables>
```

and it worked fine. I suspect this was fixed in a newer dependency than you are running.

What configuration, platform, JDK, and version of CMake plugin are you using? Can you try reproducing the problem with the 3.7.0-b1-SNAPSHOT version of the plugin?

**Comment by parched** [comment]
Ok yes, your `<key></key>` should have reproduced it if it was still broken.

I will check everything on Monday, but from memory and looking at that error message, Linux  with JDK 8, 2.8.11-b4.

**Comment by cowwoc** [comment]
Okay, so I think this is fixed. For reference, I am using JDK8 update 112 under Windows. If you still see the problem, try upgrading to update 112.

We'll wait for your report on Monday :)

**Comment by cowwoc** [comment]
I've released 3.7.0-b1 (non-SNAPSHOT) so you can test against that instead.

**Comment by parched** [comment]
Hi @cowwoc, I have tried 3.7.0-b1 with java 1.8.0_112 and I still get the exception. Maybe the difference is that I'm using Linux.

**Comment by cowwoc** [comment]
@parched Thanks for the report. I'll take a look (on Linux) later on this week.

Please send me a pom.xml that triggers the exception if you have one; otherwise, I'll work without it.

**Comment by parched** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>XXXX</artifactId>
    <groupId>com.test</groupId>
    <version>0.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <build>
        <plugins>
            <plugin>
                <groupId>com.googlecode.cmake-maven-project</groupId>
                <artifactId>cmake-maven-plugin</artifactId>
                <version>3.7.0-b1</version>
                <executions>
                    <execution>
                        <id>generate</id>
                            <goals>
                                <goal>generate</goal>
                            </goals>
                        <configuration>
                            <sourcePath>.</sourcePath>
                            <targetPath>build</targetPath>
                            <generator>Ninja</generator>
                            <classifier>linux-amd64</classifier>
                            <environmentVariables>
                                <SOME_ENV_VAR/>
                            </environmentVariables>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by cowwoc** [comment]
Thanks for the testcase. I reproduced the problem and I believe it is fixed in 3.7.0-b2-SNAPSHOT. If you confirm I will make an official release.

**Comment by parched** [comment]
Hi @cowwoc,  I will try and test if I get a chance. Looking at the code changes though, it looks like the nullptr exception will be stopped by just ignoring the variable it rather than setting it to empty which is the goal.

**Comment by cowwoc** [comment]
@parched My mistake. I misunderstood the goal. Please try the updated SNAPSHOT which sets an empty value instead.

**Comment by parched** [comment]
@cowwoc that looks better. Unfortunately I'm on holiday for a month so won't be able to test it soon. If that example I posted works for you though I'm happy to close this.

**Comment by cowwoc** [comment]
Sounds good. I'll make a release and you can confirm that this is closed when you get back. (Have a great time!)

**Comment by cowwoc** [comment]
Hey @parched,

Can you please try version 3.7.2-b1? I fixed this issue a while back but forgot to have you verify the fix.

**Comment by cowwoc** [comment]
Excellent, thanks for letting us know.
